 Bank & Customer Credit Card Analysis

Analyze bank credit card features and customer spending to recommend suitable credit cards based on eligibility and potential cashback.

Import Libraries and Load Data

In [4]:
import pandas as pd

bank_df = pd.read_excel("BankData (3).xlsx")
customer_df = pd.read_csv("customer_expense_dataset_1500.csv")

bank_df.head()

,Bank_Name,Card_Name,Annual_Fee,"Grocery_Cashback(%) [Zepto, BigBasket, etc.]",Travel_Cashback(%),"Dining_Cashback [Swiggy, Zomato, etc.](%)",Min_Income_Required(Yearly),Limit(montly),Grocery Discount,Travel_Discount,Dining_Discount,Rewards Points,Review InPoints(out of 5),CardType,Lounge access per year,Total Cashback(%)
0,ICICI,platinum ship credit card,0,1.5,2.0,15.0,300000,60000,1,8,15,0.02,4.5,credit,0.0,18.5
1,ICICI,Amazon pay icici card,0,3.0,5.0,3.0,300000,100000,3,5,10,0.00,4.0,credit,0.0,11.0
2,ICICI,Coral Credit Card,500,5.0,10.0,20.0,500000,80000,5,10,20,0.02,4.0,credit,2.0,35.0
3,IDFC,Millennia,0,1.0,0.0,0.0,300000,125000,0,0,0,150.00,1.5,credit,5.0,1.0
4,IDFC,First Classic,0,0.0,0.0,0.0,500000,150000,0,0,0,3.00,2.5,credit,6.0,0.0

In [5]:
customer_df.head()

,Name,Grocery,Travelling,Electricity,Internet,EMI,Dining,Entertainment,OTT,Ecommerce,UPI_Transactions,total Income
0,Ishaan Sharma,2860,5390,4272,1544,6265,466,4426,1482,14423,109,151958
1,Dev Desai,10322,1685,1269,843,2433,5311,5051,276,17568,31,46023
2,Aryan Chopra,10666,18942,2547,1999,2747,9167,9998,189,19118,60,160608
3,Aditya Kapoor,9734,1267,2028,1654,3556,3890,8838,20,14502,283,97435
4,Harsh Chopra,10792,10555,2561,741,11016,7513,2612,897,15787,273,171699

Data Cleaning

Basic cleaning to ensure column names are simple and missing values are handled.

In [6]:
#checking missing values and filling them with forward fill method
bank_df.isnull().sum()
bank_df.fillna(method="ffill",inplace=True)
bank_df.isnull().sum()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12504\2879434993.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  bank_df.fillna(method="ffill",inplace=True)

Bank_Name                                       0
Card_Name                                       0
Annual_Fee                                      0
Grocery_Cashback(%) [Zepto, BigBasket, etc.]    0
Travel_Cashback(%)                              0
Dining_Cashback [Swiggy, Zomato, etc.](%)       0
Min_Income_Required(Yearly)                     0
Limit(montly)                                   0
Grocery Discount                                0
Travel_Discount                                 0
Dining_Discount                                 0
Rewards Points                                  0
Review InPoints(out of 5)                       0
CardType                                        0
Lounge access per year                          0
Total Cashback(%)                               0
dtype: int64

In [7]:
customer_df.isnull().sum()

Name                0
Grocery             0
Travelling          0
Electricity         0
Internet            0
EMI                 0
Dining              0
Entertainment       0
OTT                 0
Ecommerce           0
UPI_Transactions    0
total Income        0
dtype: int64

In [8]:
#renaming column names 
bank_df.columns = [
"Bank",
"Card",
"Annual_Fee",
"Grocery_CB",
"Travel_CB",
"Dining_CB",
"Min_Income",
"Monthly_Limit",
"Grocery_Discount",
"Travel_Discount",
"Dining_Discount",
"Rewards",
"Review",
"Card_Type",
"Lounge_Access",
"Total_CB_dataset"
]

customer_df.columns = [
"Name",
"Grocery",
"Travel",
"Electricity",
"Internet",
"EMI",
"Dining",
"Entertainment",
"OTT",
"Ecommerce",
"UPI",
"Income"
]

Merge Bank and Customer Data

Merge datasets to evaluate credit card benefits based on customer spending patterns.

In [9]:
df = customer_df.merge(bank_df, how="cross")
df.head()

,Name,Grocery,Travel,Electricity,Internet,EMI,Dining,Entertainment,OTT,Ecommerce,...,Min_Income,Monthly_Limit,Grocery_Discount,Travel_Discount,Dining_Discount,Rewards,Review,Card_Type,Lounge_Access,Total_CB_dataset
0,Ishaan Sharma,2860,5390,4272,1544,6265,466,4426,1482,14423,...,300000,60000,1,8,15,0.02,4.5,credit,0.0,18.5
1,Ishaan Sharma,2860,5390,4272,1544,6265,466,4426,1482,14423,...,300000,100000,3,5,10,0.00,4.0,credit,0.0,11.0
2,Ishaan Sharma,2860,5390,4272,1544,6265,466,4426,1482,14423,...,500000,80000,5,10,20,0.02,4.0,credit,2.0,35.0
3,Ishaan Sharma,2860,5390,4272,1544,6265,466,4426,1482,14423,...,300000,125000,0,0,0,150.00,1.5,credit,5.0,1.0
4,Ishaan Sharma,2860,5390,4272,1544,6265,466,4426,1482,14423,...,500000,150000,0,0,0,3.00,2.5,credit,6.0,0.0

In [10]:
#renaming bank dataset column names for better understanding
bank_df.columns = [
"Bank",
"Card",
"Annual_Fee",
"Grocery_CB",
"Travel_CB",
"Dining_CB",
"Min_Income",
"Monthly_Limit",
"Grocery_Discount",
"Travel_Discount",
"Dining_Discount",
"Rewards",
"Review",
"Card_Type",
"Lounge_Access",
"Total_CB"
]

1 ) Best Credit Card for Grocery Shoppers

Identify credit cards offering the highest cashback for grocery purchases

In [11]:
bank_df.sort_values("Grocery_CB", ascending=False)[
["Bank","Card","Grocery_CB"]
].head()

              Bank                         Card  Grocery_CB
27  Bank of Baroda            IRCTC Credit Card        10.0
28  Bank of Baroda            Prime Credit Card        10.0
26  Bank of Baroda             HPCL Credit Card        10.0
44       Axis Bank  Axis Bank Value+ Debit Card         5.0
2            ICICI            Coral Credit Card         5.0

2 ) Cards with No Annual Fee

Find credit cards that do not charge any annual fee.

In [12]:
bank_df[bank_df["Annual_Fee"] == 0][
["Bank","Card","Annual_Fee"]
]

                   Bank                                   Card  Annual_Fee
0                 ICICI              platinum ship credit card           0
1                 ICICI                  Amazon pay icici card           0
3                  IDFC                              Millennia           0
4                  IDFC                          First Classic           0
6                  IDFC                           First Select           0
8                  IDFC                           Republic Day           0
11                  PNB                         Global Classic           0
13                  PNB                        Patanjali RuPay           0
28       Bank of Baroda                      Prime Credit Card           0
29          Canara Bank               VISA Classic Credit Card           0
30          Canara Bank                    MasterCard Standard           0
31          Canara Bank             RuPay Platinum Credit Card           0
33          Canara Bank                       RuPay Debit Card           0
34          Canara Bank                        VISA Debit Card           0
35          Canara Bank                  MasterCard Debit Card           0
36          Canara Bank                    EMV Chip Debit Card           0
43            Axis Bank           Axis Bank Delight Debit Card           0
44            Axis Bank            Axis Bank Value+ Debit Card           0
45            Axis Bank  Axis Bank Titanium Rewards Debit Card           0
46            Axis Bank          Axis Bank Platinum Debit Card           0
55            HDFC Bank                       Classic Platinum           0
56            HDFC Bank                         Platinum Debit           0
57            HDFC Bank                     Preferred Platinum           0
61            HDFC Bank                          Vishesh Debit           0
63         Federal Bank                           Visa Celesta           0
64         Federal Bank                           Visa Imperio           0
65         Federal Bank                            Visa Signet           0
66         Federal Bank                     Mastercard Celesta           0
67         Federal Bank                     Mastercard Imperio           0
68         Federal Bank                      Mastercard Signet           0
69         Federal Bank                           Rupay Signet           0
70         Federal Bank                             Rupay Wave           0
77  Kotak Mahindra Bank            Kotak UPI RuPay Credit Card           0

3 ) Cards Suitable Based on Income

Filter cards that customers are eligible for based on their annual income.

In [13]:
eligible = df[(df["Income"] * 12) >= df["Min_Income"]]

eligible_cards = (
    eligible.groupby("Name")["Card"]
    .apply(lambda x: ", ".join(sorted(set(x))))
    .reset_index(name="Eligible_Cards")
)

eligible_cards

              Name                                     Eligible_Cards
0    Aarav Agarwal  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
1     Aarav Bansal  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
2     Aarav Chopra  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
3      Aarav Desai  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
4      Aarav Gupta  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
..             ...                                                ...
385       Yash Rao  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
386     Yash Reddy  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
387    Yash Sharma  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
388     Yash Singh  Ace, Airtel Axis Bank Credit Card, Amazon pay ...
389     Yash Verma  Ace, Airtel Axis Bank Credit Card, Amazon pay ...

[390 rows x 2 columns]

4 ) Calculate Total Cashback

Calculate total cashback earned by customers based on their spending in grocery, travel, and dining categories.

In [14]:
df["Total_Cashback"] = (
df["Grocery"] * df["Grocery_CB"]/100 +
df["Travel"] * df["Travel_CB"]/100 +
df["Dining"] * df["Dining_CB"]/100
)

df[["Name","Bank","Card","Total_Cashback"]]

,Name,Bank,Card,Total_Cashback
0,Ishaan Sharma,ICICI,platinum ship credit card,220.60
1,Ishaan Sharma,ICICI,Amazon pay icici card,369.28
2,Ishaan Sharma,ICICI,Coral Credit Card,775.20
3,Ishaan Sharma,IDFC,Millennia,28.60
4,Ishaan Sharma,IDFC,First Classic,0.00
...,...,...,...,...
116995,Sai Patel,Kotak Mahindra Bank,IndianOil Kotak Credit Card,251.56
116996,Sai Patel,Kotak Mahindra Bank,Zen Signature Credit Card,0.00
116997,Sai Patel,Kotak Mahindra Bank,Kotak Air Credit Card,524.19
116998,Sai Patel,Kotak Mahindra Bank,PVR INOX Kotak Credit Card,684.45
116999,Sai Patel,Kotak Mahindra Bank,Kotak UPI RuPay Credit Card,0.00

5 ) Best Dining Cashback Cards

 Identify credit cards that provide the highest cashback percentage for dining expenses.

In [15]:
bank_df.sort_values("Dining_CB", ascending=False)[
["Bank","Card","Dining_CB"]
].head()

         Bank                          Card  Dining_CB
43  Axis Bank  Axis Bank Delight Debit Card       25.0
2       ICICI             Coral Credit Card       20.0
0       ICICI     platinum ship credit card       15.0
15      IDBI       IDBI Delight Credit Card       15.0
16      IDBI          Royale Signature card       15.0

6 ) Compare Annual Fee and Cashback

Compare credit card annual fees with the cashback customers can earn.

In [16]:
fee_vs_cashback = df[["Name","Bank","Card","Annual_Fee","Total_Cashback"]]

fee_vs_cashback.sample(10)

,Name,Bank,Card,Annual_Fee,Total_Cashback
93173,Rohan Iyer,Axis Bank,Flipkart Axis Bank Credit Card,500,409.290
51912,Ishaan Pillai,Axis Bank,Axis Bank MyZone Credit Card,500,133.030
18436,Atharva Sharma,Bank of Baroda,Prime Credit Card,0,3218.300
40898,Aryan Kapoor,Bank of Baroda,HPCL Credit Card,499,2919.650
102020,Yash Pillai,Kotak Mahindra Bank,Zen Signature Credit Card,1500,0.000
24009,Harsh Singh,Federal Bank,Visa Celesta,0,0.000
77005,Sai Jain,SBI,SimplyCLICK SBI Card,499,0.000
6838,Harsh Jain,HDFC Bank,Diners Club Privilege,1000,501.800
5563,Arjun Jain,SBI,SBI Platinum International Debit Card,300,0.000
10430,Arjun Gupta,HDFC Bank,Platinum Debit,0,24.125

7 ) Cards Suitable Based on Monthly Limit

Identify cards whose monthly credit limit can support customer spending.

In [17]:
df["Total_Spending"] = df["Grocery"] + df["Travel"] + df["Dining"]

valid_cards = df[df["Monthly_Limit"] >= df["Total_Spending"]]

best_card = (
    valid_cards.sort_values("Monthly_Limit")
    .groupby("Name")
    .first()
    .reset_index()
)

best_card[["Name","Bank","Card","Monthly_Limit","Total_Spending"]]

,Name,Bank,Card,Monthly_Limit,Total_Spending
0,Aarav Agarwal,Canara Bank,VISA Classic Credit Card,20000,6753
1,Aarav Bansal,Canara Bank,VISA Classic Credit Card,20000,13238
2,Aarav Chopra,Canara Bank,VISA Classic Credit Card,20000,16025
3,Aarav Desai,Canara Bank,MasterCard Standard,20000,15233
4,Aarav Gupta,Canara Bank,MasterCard Standard,20000,14209
...,...,...,...,...,...
385,Yash Rao,Canara Bank,RuPay Platinum Credit Card,40000,31047
386,Yash Reddy,Canara Bank,RuPay Platinum Credit Card,40000,37587
387,Yash Sharma,Canara Bank,VISA Classic Credit Card,20000,17363
388,Yash Singh,Canara Bank,MasterCard Standard,20000,11564
389,Yash Verma,Canara Bank,MasterCard Standard,20000,11878

8 ) Cards with Highest Reward Points

Identify credit cards that offer the highest reward points, helping customers maximize reward benefits.

In [18]:
bank_df.sort_values("Rewards", ascending=False)[
["Bank","Card","Rewards"]
].head(10)

         Bank                       Card  Rewards
38  Axis Bank  Axis Bank Neo Credit Card    200.0
9         PNB            Global Platinum    150.0
3        IDFC                  Millennia    150.0
13        PNB            Patanjali RuPay    150.0
10        PNB                Global Gold    100.0
12        PNB                 Millennial    100.0
11        PNB             Global Classic     50.0
53  HDFC Bank    Diners Club Black Metal     10.0
50  HDFC Bank                    Freedom     10.0
54  HDFC Bank              Infinia Metal     10.0

9 ) Cards Offering Lounge Access

Find credit cards that provide airport lounge access, which is a premium travel benefit.

In [19]:
bank_df[bank_df["Lounge_Access"] > 0][
["Bank","Card","Lounge_Access"]
]

                   Bank                                   Card  Lounge_Access
2                 ICICI                      Coral Credit Card            2.0
3                  IDFC                              Millennia            5.0
4                  IDFC                          First Classic            6.0
5                  IDFC                            WOW ! Black            4.0
6                  IDFC                           First Select            6.0
8                  IDFC                           Republic Day            4.0
9                   PNB                        Global Platinum            8.0
10                  PNB                            Global Gold            2.0
12                  PNB                             Millennial            2.0
16                IDBI                   Royale Signature card            4.0
17                IDBI                IDBI Euphoria World card            4.0
18                  SBI                      Cashback SBI Card            4.0
21                  SBI                         SBI Card Prime           12.0
22                  SBI                         SBI Card ELITE           14.0
25                  SBI  SBI Platinum International Debit Card            4.0
26       Bank of Baroda                       HPCL Credit Card            4.0
27       Bank of Baroda                      IRCTC Credit Card            4.0
29          Canara Bank               VISA Classic Credit Card            2.0
30          Canara Bank                    MasterCard Standard            2.0
31          Canara Bank             RuPay Platinum Credit Card            5.0
32          Canara Bank                Canara Gold Credit Card            5.0
33          Canara Bank                       RuPay Debit Card            2.0
34          Canara Bank                        VISA Debit Card            2.0
35          Canara Bank                  MasterCard Debit Card            2.0
36          Canara Bank                    EMV Chip Debit Card            2.0
37            Axis Bank              Axis Bank ACE Credit Card            4.0
40            Axis Bank           Airtel Axis Bank Credit Card            4.0
41            Axis Bank         Flipkart Axis Bank Credit Card            4.0
42            Axis Bank           Axis Bank MyZone Credit Card            4.0
43            Axis Bank           Axis Bank Delight Debit Card            4.0
55            HDFC Bank                       Classic Platinum            8.0
56            HDFC Bank                         Platinum Debit            8.0
57            HDFC Bank                     Preferred Platinum            8.0
58            HDFC Bank                        Millennia Debit            4.0
61            HDFC Bank                          Vishesh Debit            8.0
62            HDFC Bank                          Giga Business            4.0
63         Federal Bank                           Visa Celesta            2.0
64         Federal Bank                           Visa Imperio            6.0
65         Federal Bank                            Visa Signet            2.0
66         Federal Bank                     Mastercard Celesta            2.0
67         Federal Bank                     Mastercard Imperio            6.0
68         Federal Bank                      Mastercard Signet            2.0
69         Federal Bank                           Rupay Signet            1.0
70         Federal Bank                             Rupay Wave            1.0
74  Kotak Mahindra Bank              Zen Signature Credit Card            2.0
75  Kotak Mahindra Bank                  Kotak Air Credit Card            4.0

10 ) Final Credit Card Recommendation

Recommend the best credit card for each customer based on the maximum cashback they can earn from their spending.

In [20]:
# Step 1: keep only cards customer is eligible for
eligible_cards = df[(df["Income"] * 12) >= df["Min_Income"]]

# Step 2: choose card with highest cashback for each customer
best_cards = (
    eligible_cards.sort_values("Total_Cashback", ascending=False)
    .groupby("Name")
    .first()
    .reset_index()
)

best_cards[["Name","Income","Bank","Card","Total_Cashback"]].head(40)

,Name,Income,Bank,Card,Total_Cashback
0,Aarav Agarwal,140511,ICICI,Coral Credit Card,3707.95
1,Aarav Bansal,60878,ICICI,Coral Credit Card,4165.90
2,Aarav Chopra,89550,ICICI,Coral Credit Card,3068.50
3,Aarav Desai,95982,ICICI,Coral Credit Card,4602.05
4,Aarav Gupta,156063,ICICI,Coral Credit Card,3628.45
5,Aarav Iyer,103984,ICICI,Coral Credit Card,4716.00
6,Aarav Jain,127467,ICICI,Coral Credit Card,2603.15
7,Aarav Joshi,74825,ICICI,Coral Credit Card,4247.65
8,Aarav Kapoor,81199,ICICI,Coral Credit Card,3572.60
9,Aarav Malhotra,122341,ICICI,Coral Credit Card,3833.55
10,Aarav Mehta,117725,ICICI,Coral Credit Card,4317.15
11,Aarav Mishra,103010,ICICI,Coral Credit Card,3177.50
12,Aarav Nair,178040,Bank of Baroda,HPCL Credit Card,3400.75
13,Aarav Patel,104069,ICICI,Coral Credit Card,5104.35
14,Aarav Pillai,75790,Bank of Baroda,Prime Credit Card,3725.00
15,Aarav Rao,167925,ICICI,Coral Credit Card,3776.85
16,Aarav Reddy,86534,ICICI,Coral Credit Card,4142.95
17,Aarav Sharma,177605,Bank of Baroda,Prime Credit Card,4211.05
18,Aarav Singh,44995,ICICI,Coral Credit Card,4408.05
19,Aarav Verma,47413,ICICI,Coral Credit Card,4615.20
20,Aditya Agarwal,106717,ICICI,Coral Credit Card,4334.00
21,Aditya Bansal,129977,Bank of Baroda,HPCL Credit Card,3001.55
22,Aditya Chopra,56105,ICICI,Coral Credit Card,4921.40
23,Aditya Desai,103686,ICICI,Coral Credit Card,4078.75
24,Aditya Gupta,46730,ICICI,Coral Credit Card,4598.35
25,Aditya Iyer,143153,Bank of Baroda,HPCL Credit Card,4006.30
26,Aditya Jain,151961,ICICI,Coral Credit Card,4104.35
27,Aditya Joshi,72771,ICICI,Coral Credit Card,3479.15
28,Aditya Kapoor,116724,ICICI,Coral Credit Card,3931.40
29,Aditya Malhotra,150906,ICICI,Coral Credit Card,3634.80
30,Aditya Mehta,103788,ICICI,Coral Credit Card,4649.15
31,Aditya Mishra,186926,ICICI,Coral Credit Card,4334.85
32,Aditya Nair,86503,ICICI,Coral Credit Card,3511.90
33,Aditya Patel,134211,Bank of Baroda,Prime Credit Card,3228.75
34,Aditya Pillai,42318,ICICI,Coral Credit Card,3168.35
35,Aditya Rao,45982,ICICI,Coral Credit Card,3150.55
36,Aditya Reddy,79992,ICICI,Coral Credit Card,4105.40
37,Aditya Sharma,37868,IDBI,IDBI Delight Credit Card,4621.65
38,Aditya Singh,136115,ICICI,Coral Credit Card,4107.10
39,Aditya Verma,85426,ICICI,Coral Credit Card,3268.20